env:
  browser: true
  es2020: true
  es6: true
  node: true
extends:
  - google
  - eslint:recommended
  - react-app
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended
plugins:
  - "@jambit/typed-redux-saga"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
rules:
  require-jsdoc: 0
ignorePatterns:
  - "**/*.js"
overrides:
  - 
    files:
      - "*.{ts,tsx}"
    rules:
      new-cap: 0
      react/prop-types: 0
      "@typescript-eslint/explicit-module-boundary-types": 0
  -
    files:
      - "*.ts"
    excludedFiles:
      - "./**/*.spec.ts"
    rules:
      "@jambit/typed-redux-saga/use-typed-effects": "error"
      "@jambit/typed-redux-saga/delegate-effects": "error"
settings:
  react:
    version: detect
