name: Deploy Master Server to Google App Engine on merge
'on':
  push:
    branches:
      - master
    paths:
      - src/games/**
      - src/envs/**
      - src/server/master/**
      - yarn.lock
      - app.yaml
      - .github/workflows/deploy_master.yml
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GAE_SA_KEY }}
