name: Deploy Master Server to Google App Engine on merge
'on':
  push:
    branches:
      - master
    paths:
      - .env*
      - yarn.lock
      - app.yaml
      - package.json
      - .github/workflows/deploy_master.yml
      - src/games/**
      - src/server/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn typecheck:server
      - run: yarn test
      - run: yarn lint:ts
      - run: yarn build:games
      - run: yarn build:server
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GAE_SA_KEY }}
