# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Builder

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened, auto_merge_enabled]
    paths-ignore:
      - "README.md"
      - ".vscode/**"

env:
  node-version: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - run: yarn
    - run: yarn typecheck
    - run: yarn test
    - run: yarn lint
    - run: yarn build
